### ISSUE TITLE
edit and delete icons

### ISSUE THREAD

**Issue by stinkyjoint** [sayghteight/ANetworks#22]
icons have disapeared from the buttons
![untitled](https://user-images.githubusercontent.com/34556942/35016838-4fd7b9be-fb12-11e7-90cc-27b2ea02d4a1.png)

**Comment by sayghteight** [comment]
It may be damaged or a temporary crash on the servers of FontAwesome CDN.

I can not reproduce the failure in localhost.

**Comment by sayghteight** [comment]
Try using the following code in Header

aplications/views/header.php

`<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">`

**Comment by stinkyjoint** [comment]
failed, this worked before i did a full update of your new files

**Comment by stinkyjoint** [comment]
fixed the issue

there was an issue in assets/new/style.css, i changed the http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css to a https

**Comment by sayghteight** [comment]
Thanks, in the next commit it will be fixed.
