### ISSUE TITLE
nginx doesn't work

### ISSUE THREAD

**Issue by Mysterium** [sayghteight/ANetworks#25]
Hey

want to setup the page on nginx (debian), but can't it to run because of the rewrite rules
nginx dosn't use .htaccess files :/

**Comment by sayghteight** [comment]
I started with a small patch for Nginx, I hope to release it soon.

**Comment by sayghteight** [comment]
**Delete .htacces and in your nginx config**

`# nginx configuration 
location / 
{ if (!-e $request_filename)
{ rewrite ^(.*)$ /index.php/$0 break; } }
`
